GameMvc/Controllers/CharacterController.cs
using System.Linq;
using System.Web.Mvc;
using GameLogic.Game;

namespace GameMvc.Controllers
{
    public class CharacterController : Controller
    {
        [HttpPost]
        public ActionResult SelectSkill(string skillName)
        {
            var g = (Game)Session["Game"];
            var skill = g.Player.SkillTree.Get().First(i => i.Name == skillName);
            g.Player.ChooseSkill(skill);
            //var tournamentPlayer = g.Tournament.Participants.First(p => p.Character is Player);
            //var skill = tournamentPlayer.Character.SkillTree.Get().First(i => i.Name == skillName);
            //((Player) tournamentPlayer.Character).ChooseSkill(skill);
            //g.Player = tournamentPlayer.Character as Player;
            Session["Game"] = g;
            return View("~/Views/Home/Character/SkillTree.cshtml", g.Player);
        }
    }
}

GameMvc/Controllers/GameController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using GameLogic.Characters.CharacterHelpers;
using GameLogic.Characters.Player;
using GameLogic.Enums;
using GameLogic.Equipment.Shields;
using GameLogic.Equipment.Weapons;
using GameLogic.Game;
using GameMvc.Models;

namespace GameMvc.Controllers
{
    public class GameController : Controller
    {
        //
        // GET: /Game/

        [HttpPost]
        public ActionResult CreateCharacter(UiCharacterModel model)
        {
            if (!ModelState.IsValid)
            {
                return View("~/Views/Home/Index.cshtml", model);
            }
            var g = (Game)Session["Game"];
            g.Player = new Player();
            g.Player.SetName(model.Name);
            return View("~/Views/Home/Character.cshtml", g.Player);

        }

        [HttpPost]
        public ActionResult CheckChooseOpponent()
        {
            var game = (Game) Session["Game"];
            if (game.CurrentBattleDetails.BattleStatus == BattleStatus.NotStarted)
            {
                return View("~/Views/Game/ChooseOpponent.cshtml", new UiAvailableOpponentsModel
                {
                    Opponents = game.GetPossibleOpponents()
                });
            }
            return null;
        }

        [HttpPost]
        public ActionResult CheckBattleStatus()
        {
            var game = (Game)Session["Game"];
            if (game.CurrentBattleDetails.BattleStatus != BattleStatus.BattleOver)
            {
                return null;
            }

            var br = game.BuildBattleReport(game.CurrentBattleDetails);
            return View("~/Views/Game/BattleOver.cshtml", br);
        }

        [HttpPost]
        public ActionResult ProcessBattleOver()
        {
            var game = (Game) Session["Game"];
            game.ProcessBattleOver();
            Session["Game"] = game;
            return null;
        }

        public ActionResult ChooseOpponent(string name)
        {
            var game = (Game) Session["Game"];
            if (game.CurrentBattleDetails.BattleStatus != BattleStatus.NotStarted)
            {
                throw new Exception("WTF YOU CANT CHOOSE AN OPPONENT YOU ALREADY HAVE ONE");
            }

            var opponent = game.GetPossibleOpponents().First(i => i.Name == name);
            if (opponent == null)
            {
                throw new Exception("THAT OPPONENT DOESNT EXIST WHAT ARE YOU DOING");
            }
            EquipmentHelper.EquipEquipment(opponent, new BlessedCardboard());
            EquipmentHelper.EquipEquipment(opponent, new Sword());
            game.ChooseOpponent(opponent);
            Session["Game"] = game;

            return View("~/Views/Home/Arena.cshtml", game.CurrentBattleDetails);
        }

        public ActionResult PerformPlayerAction(string actionName)
        {
            var game = (Game) Session["Game"];
            var action = game.Player.CurrentAvailableActions.First(i => i.Name == actionName);
            game.PerformPlayerAction(action);
            game.PerformAITurn();
            Session["Game"] = game;
            return View("~/Views/Home/Arena.cshtml", game.CurrentBattleDetails);
        }
    }
}

GameMvc/Views/Game/BattleOver.cshtml
@using GameLogic.Enums
@model GameLogic.Game.BattleReport

@section scripts{
    <script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>
}

@{
    Layout = Request.IsAjaxRequest() ? null : "~/Views/Shared/_Layout.cshtml";
}


@if (Model.BattleStatus == BattleStatus.BattleOver)
{
    <text>The battle is over!</text>
    if (Model.PlayerWins)
    {
        <text>YOU WIN!</text>
    }
    else
    {
        <text>YOU LOSE!</text>
    }

    <input id="btnBattleOver" type="button" value="OK"/>
}

GameMvc/Views/Game/ChooseOpponent.cshtml
@model GameMvc.Models.UiAvailableOpponentsModel
           
@section scripts{
    <script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>
}

@{
    Layout = Request.IsAjaxRequest() ? null : "~/Views/Shared/_Layout.cshtml";
}

<div>
    <ul id="opponentList">
        @foreach (var o in Model.Opponents)
        {
            <li>@Html.ActionLink(@o.Name, "ChooseOpponent", "Game", new { name = @o.Name }, null)</li>
        }
    </ul>
    <br/>
    @Html.ActionLink("I'm scared - get me out of here!", "Character", "Home")
</div>